import { Resend } from 'resend';
import { NextResponse } from 'next/server';

import { db } from '@/firebase';
import { Certification } from '@/types/certifications';
import { getDocs, collection } from '@/firebaseStubs';

export const runtime = "nodejs";

export async function GET(request: Request) {
  try {
    const apiKey = process.env.RESEND_API_KEY;
    if (!apiKey) {
      console.error("CERT_NOTIFY: RESEND_API_KEY is missing");
      return NextResponse.json({ error: "Email service is not configured (Missing API Key)." }, { status: 500 });
    }

    const { searchParams } = new URL(request.url);
    const testMode = searchParams.get('test') === 'true';
    const testRecipient = searchParams.get('email');

    const resend = new Resend(apiKey);
    
    // Fetch all certifications
    const snapshot = await getDocs(collection(db, "certifications"));
    const certifications = snapshot.docs.map((doc: any) => ({
      id: doc.id,
      ...doc.data()
    })) as Certification[];

    const now = new Date();
    // Normalize "now" to midnight for comparison
    const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());

    const milestones = [30, 60, 90];
    const expiringItems: { cert: Certification, daysLeft: number }[] = [];

    certifications.forEach(cert => {
      if (!cert.expirationDate) return;
      
      const expDate = new Date(cert.expirationDate);
      // Normalize expiration date to midnight for comparison
      const expMidnight = new Date(expDate.getFullYear(), expDate.getMonth(), expDate.getDate());
      
      const diffTime = expMidnight.getTime() - today.getTime();
      const diffDays = Math.round(diffTime / (1000 * 60 * 60 * 24));

      if (milestones.includes(diffDays) || (testMode && diffDays > 0)) {
        expiringItems.push({ cert, daysLeft: diffDays });
      }
    });

    if (expiringItems.length === 0) {
      return NextResponse.json({ message: "No certifications hitting milestones today.", checked: certifications.length });
    }

    // Default recipients
    const recipients = testRecipient ? [testRecipient] : ["todd@pmcdecor.com", "rick@pmcdecor.com", "shelly@pmcdecor.com"];

    const htmlContent = `
      <div style="font-family: sans-serif; padding: 20px; border: 1px solid #eee; border-radius: 8px; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #15616D; border-bottom: 2px solid #15616D; padding-bottom: 10px;">Certification Expiration Alert</h2>
        <p>The following employee certifications are reaching expiration milestones (30, 60, or 90 days out):</p>
        <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 14px;">
          <thead>
            <tr style="background-color: #f8f9fa;">
              <th style="padding: 10px; border: 1px solid #dee2e6; text-align: left;">Employee</th>
              <th style="padding: 10px; border: 1px solid #dee2e6; text-align: left;">Certification</th>
              <th style="padding: 10px; border: 1px solid #dee2e6; text-align: left;">Expires</th>
              <th style="padding: 10px; border: 1px solid #dee2e6; text-align: center;">Days Left</th>
            </tr>
          </thead>
          <tbody>
            ${expiringItems.sort((a,b) => a.daysLeft - b.daysLeft).map(item => `
              <tr>
                <td style="padding: 10px; border: 1px solid #dee2e6;">${item.cert.employeeName}</td>
                <td style="padding: 10px; border: 1px solid #dee2e6;">${item.cert.type}</td>
                <td style="padding: 10px; border: 1px solid #dee2e6;">${item.cert.expirationDate}</td>
                <td style="padding: 10px; border: 1px solid #dee2e6; text-align: center; font-weight: bold; color: ${item.daysLeft <= 30 ? '#dc3545' : '#856404'};">
                  ${item.daysLeft}
                </td>
              </tr>
            `).join('')}
          </tbody>
        </table>
        <div style="margin-top: 20px; padding: 15px; background-color: #fff3cd; color: #856404; border-radius: 4px; border: 1px solid #ffeeba;">
          <strong>Action Required:</strong> Please ensure these employees are scheduled for renewal or updated in the system.
        </div>
        <p style="font-size: 12px; color: #666; margin-top: 20px; text-align: center;">
          Automatically generated by PMC Analytics Tool • ${new Date().toLocaleDateString()}
        </p>
      </div>
    `;

    const { data, error } = await resend.emails.send({
      from: 'PMC Notifications <dispatch@pmcdecor.com>',
      to: recipients,
      subject: `Certification Alert: ${expiringItems.length} Certifications Expiring Soon`,
      html: htmlContent,
    });

    if (error) {
      console.error("RESEND ERROR:", error);
      return NextResponse.json({ error }, { status: 400 });
    }

    return NextResponse.json({ 
      success: true, 
      message: "Notification emails sent", 
      count: expiringItems.length, 
      recipients 
    });
  } catch (err: any) {
    console.error("CRITICAL ERROR in cert-notifications:", err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
