import type { Metadata } from "next";
import "./globals.css";
import AppChrome from "@/components/AppChrome";
import { initializePermissions } from "@/lib/permissions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Kick off permission initialization without blocking route render.
  initializePermissions().catch((error) => {
    console.error("Failed to initialize permissions:", error);
  });

  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <AppChrome>{children}</AppChrome>
      </body>
    </html>
  );
}
