import type { HelpGuideSummary } from './types.ts';

// Keep this small: navigation and the directory do not need the full guide text.
export const HELP_GUIDE_SUMMARIES: readonly HelpGuideSummary[] = [
  { slug: 'home', title: 'Home', category: 'Getting started', pagePath: '/', pageLabel: 'Home', pagePermission: 'home', summary: 'Your starting point for personal updates, assignments, company information, and upcoming time off.', quickStart: 'Check the date window in your personal update, then open the item you need to act on.' },
  { slug: 'my-work', title: 'My Work', category: 'Getting started', pagePath: '/pm-dashboard', pageLabel: 'My Work', pagePermission: 'pm-dashboard', summary: 'Your assigned RFIs, tasks, meetings, and connected Outlook events over the next five workdays.', quickStart: 'Review overdue items first, then select a project to focus your daily work.' },
  { slug: 'open-changes', title: 'Open Changes', category: 'Projects & estimating', pagePath: '/pm-dashboard/changes', pageLabel: 'Open Changes', pagePermission: 'pm-dashboard', summary: 'Follow open change events and change orders for your projects.', quickStart: 'Choose a project and change type, then open the source record to review its next step.' },
  { slug: 'dashboard', title: 'Dashboard', category: 'Projects & estimating', pagePath: '/dashboard', pageLabel: 'Dashboard', pagePermission: 'dashboard', summary: 'An estimating overview of bid activity, customers, sales, hours, and project statuses.', quickStart: 'Start with the unfiltered totals, then narrow the date range and open a summary to see its jobs.' },
  { slug: 'projects', title: 'Projects', category: 'Projects & estimating', pagePath: '/projects', pageLabel: 'Projects', pagePermission: 'projects', summary: 'Find project records and inspect their estimating and Procore details.', quickStart: 'Search for the job and verify its customer and project identifiers before reviewing details.' },
  { slug: 'estimating', title: 'Estimating', category: 'Projects & estimating', pagePath: '/estimating-tools', pageLabel: 'Estimating', pagePermission: 'estimating-tools', summary: 'Calculate concrete and reinforcing quantities and save project estimating breakdowns.', quickStart: 'Select a project and calculator, then check dimension units before entering quantities.' },
  { slug: 'constants', title: 'Constants', category: 'Projects & estimating', pagePath: '/constants', pageLabel: 'Constants', pagePermission: 'constants', summary: 'Maintain shared estimating values and the rebar reference table.', quickStart: 'Find the named constant and confirm its unit and category before changing its value.' },
  { slug: 'kpi', title: 'KPI', category: 'Reports & financials', pagePath: '/kpi', pageLabel: 'KPI', pagePermission: 'kpi', summary: 'Review monthly sales, win rate, revenue, labor, profit, and lead-time measures.', quickStart: 'Choose the year and read each table heading before comparing actual results with goals.' },
  { slug: 'wip', title: 'WIP', category: 'Reports & financials', pagePath: '/wip', pageLabel: 'WIP', pagePermission: 'wip', summary: 'See how labor and scheduled sales are distributed across the work schedule.', quickStart: 'Filter the year and project, then compare the table with the monthly hours view.' },
  { slug: 'financial-wip', title: 'Financial WIP', category: 'Reports & financials', pagePath: '/analytics/monthly-hours', pageLabel: 'Financial WIP', pagePermission: 'analytics', summary: 'Review sold contracts, unbilled backlog, remaining labor hours, and financial lead time.', quickStart: 'Open the sold or backlog detail and check status, date source, contract source, and billing.' },
  { slug: 'cost-code-profitability', title: 'Cost Code P&L', category: 'Reports & financials', pagePath: '/analytics/cost-code-sales', pageLabel: 'Cost Code P&L', pagePermission: 'analytics-cost-code-sales', fallbackPermission: 'analytics', summary: 'Compare estimated sales and costs by work category, then inspect project-level QuickBooks actual costs.', quickStart: 'Select the period and status, then drill from a top-level group into reporting groups and cost codes.' },
  { slug: 'qbo-project-profitability', title: 'QBO P&L', category: 'Reports & financials', pagePath: '/accounting/project-profitability', pageLabel: 'QBO P&L', pagePermission: 'accounting-project-profitability', fallbackPermission: 'admin', summary: 'Review recorded project sales, actual costs, profit, billing, and accounts receivable from QuickBooks.', quickStart: 'Check the snapshot date and reporting window, then expand a project to inspect its transactions.' },
  { slug: 'qbo-direct-costs', title: 'QBO Direct Costs', category: 'Reports & financials', pagePath: '/accounting/direct-cost-bills', pageLabel: 'QBO Direct Costs', pagePermission: 'accounting-direct-cost-bills', fallbackPermission: 'admin', summary: 'Review monthly Procore-derived project costs and prepare the corresponding QuickBooks bill.', quickStart: 'Choose the month and review a project’s source lines, mappings, and issues before saving a bill.' },
  { slug: 'analytics', title: 'Analytics / Field Productivity', category: 'Reports & financials', pagePath: '/analytics', pageLabel: 'Analytics', pagePermission: 'analytics', summary: 'Compare purchase-order quantities with logged usage and inspect associated field labor.', quickStart: 'Choose a project, expand a purchase order, and compare expected, used, and remaining quantities.' },
  { slug: 'field-productivity', title: 'Field Productivity', category: 'Reports & financials', pagePath: '/analytics/productivity', pageLabel: 'Field Productivity', pagePermission: 'analytics', summary: 'The direct Field Productivity page, also available through Analytics.', quickStart: 'Choose By PO or By Description, then expand a line to review its logs and timecards.' },
  { slug: 'market-outlook', title: 'Market Outlook', category: 'Reports & financials', pagePath: '/market-outlook', pageLabel: 'Market Outlook', pagePermission: 'analytics', summary: 'Read published construction-market indicators and their planning implications.', quickStart: 'Check the snapshot and source dates, then distinguish local evidence from national indicators.' },
  { slug: 'reporting', title: 'Reporting', category: 'Reports & financials', pagePath: '/reporting', pageLabel: 'Reporting', pagePermission: 'reporting', summary: 'Build a project and date-range report from timecards or productivity logs.', quickStart: 'Choose the report type, project, and date range before generating the report.' },
  { slug: 'wip-schedule', title: 'Wip Schedule', category: 'Scheduling & field work', pagePath: '/scheduling', pageLabel: 'Wip Schedule', pagePermission: 'scheduling', summary: 'Allocate project labor hours to months and compare allocations with available project hours.', quickStart: 'Find the project and compare Total Hours with Total Scheduled before adjusting monthly allocations.' },
  { slug: 'project-gantt', title: 'Project Gantt', category: 'Scheduling & field work', pagePath: '/project-schedule', pageLabel: 'Project Gantt', pagePermission: 'project-schedule', summary: 'Plan the timing and labor of individual project scopes on a visual timeline.', quickStart: 'Select the project, inspect its scopes, and choose a day, week, or month view.' },
  { slug: 'long-term', title: 'Long-Term', category: 'Scheduling & field work', pagePath: '/long-term-schedule', pageLabel: 'Long-Term', pagePermission: 'long-term-schedule', summary: 'Plan work across projects, scopes, dates, and project managers.', quickStart: 'Locate the project and scope, then check existing assignments before placing future work.' },
  { slug: 'short-term', title: 'Short-Term', category: 'Scheduling & field work', pagePath: '/short-term-schedule', pageLabel: 'Short-Term', pagePermission: 'short-term-schedule', summary: 'Arrange near-term field work and review daily capacity.', quickStart: 'Choose the working dates, add the project and scope, and check the capacity display.' },
  { slug: 'crew-dispatch', title: 'Crew Dispatch', category: 'Scheduling & field work', pagePath: '/daily-crew-dispatch-board', pageLabel: 'Crew Dispatch', pagePermission: 'crew-dispatch', summary: 'Coordinate daily crew assignments, absences, scheduled work, and concrete orders.', quickStart: 'Check the dispatch date and who is available before assigning people to work.' },
  { slug: 'concrete-orders', title: 'Concrete Orders', category: 'Scheduling & field work', pagePath: '/concrete-orders-schedule', pageLabel: 'Concrete Orders', pagePermission: 'concrete-orders-schedule', summary: 'Review concrete orders alongside scheduled project work.', quickStart: 'Locate the project and pour date, then check order details against the field schedule.' },
  { slug: 'crew-management', title: 'Crew Management', category: 'People & equipment', pagePath: '/crew-management', pageLabel: 'Crew Management', pagePermission: 'crew-management', summary: 'Maintain the standard right-hand person and laborers assigned to each foreman’s crew.', quickStart: 'Find the foreman, select crew members, and save that crew’s assignment.' },
  { slug: 'employees', title: 'Employees', category: 'People & equipment', pagePath: '/employees', pageLabel: 'Employees', pagePermission: 'employees', summary: 'Manage employee records, app access, time off, and certifications.', quickStart: 'Search or filter the employee list, then open the correct person’s record.' },
  { slug: 'certifications', title: 'Certifications', category: 'People & equipment', pagePath: '/certifications', pageLabel: 'Certifications', pagePermission: 'certifications', summary: 'Track employee certification types and expiration dates.', quickStart: 'Find the employee and compare the recorded expiration date with the current credential.' },
  { slug: 'equipment', title: 'Equipment', category: 'People & equipment', pagePath: '/equipment', pageLabel: 'Equipment', pagePermission: 'equipment', summary: 'Maintain equipment inventory and assign assets to projects and dates.', quickStart: 'Select an asset, inspect its active schedule, and check dates before adding an assignment.' },
  { slug: 'holidays', title: 'Holidays', category: 'People & equipment', pagePath: '/holidays', pageLabel: 'Holidays', pagePermission: 'holidays', summary: 'Maintain the company holiday calendar and paid-holiday designation.', quickStart: 'Review the date and policy notes before adding or editing a holiday.' },
  { slug: 'onboarding', title: 'Onboarding', category: 'People & equipment', pagePath: '/onboarding/submissions', pageLabel: 'Onboarding', pagePermission: 'onboarding', summary: 'Review personnel submissions, payroll processing status, and handbook compliance.', quickStart: 'Choose Payroll or Handbook, then open the employee’s submission or compliance record.' },
  { slug: 'handbook', title: 'Handbook', category: 'People & equipment', pagePath: '/employees/handbook', pageLabel: 'Handbook', pagePermission: 'handbook', summary: 'Read the company handbook and complete the available acknowledgment.', quickStart: 'Use the page and zoom controls to read the handbook, then review the signoff instructions.' },
  { slug: 'manage-kpis', title: 'Manage (KPI Cards)', category: 'Administration & integrations', pagePath: '/kpi-cards-management', pageLabel: 'Manage', pagePermission: 'kpi-cards-management', summary: 'Maintain the saved monthly values and rows shown in KPI cards.', quickStart: 'Choose the editing year and card before changing a monthly value.' },
  { slug: 'procore', title: 'Procore', category: 'Administration & integrations', pagePath: '/procore', pageLabel: 'Procore', pagePermission: 'procore', summary: 'An integration workspace for Procore connection checks, sync tools, and controlled maintenance.', quickStart: 'Check connection status and identify the specific tool and project you need.' },
  { slug: 'timecards', title: 'Timecards', category: 'Administration & integrations', pagePath: '/procore/timecard-entries', pageLabel: 'Timecards', pagePermission: 'procore-timecards', fallbackPermission: 'procore', summary: 'Synchronize and inspect Procore timecard entries and time types.', quickStart: 'Confirm the connection and date filters, then use Sync Entries for the intended data.' },
  { slug: 'line-items', title: 'Line Items', category: 'Projects & estimating', pagePath: '/procore/proposal-line-items-live', pageLabel: 'Line Items', pagePermission: 'procore-line-items', fallbackPermission: 'procore', summary: 'Inspect project estimating lines, budget details, and commercial-data coverage.', quickStart: 'Filter to one project and expand its proposal or budget rows.' },
  { slug: 'commitments', title: 'Commitments', category: 'Projects & estimating', pagePath: '/procore/commitments-live', pageLabel: 'Commitments', pagePermission: 'procore-commitments', fallbackPermission: 'procore', summary: 'Inspect purchase-order and commitment change-order lines by project and vendor.', quickStart: 'Filter the project and source type, then compare quantities, unit costs, and line amounts.' },
  { slug: 'commitment-maker', title: 'Commitment Maker', category: 'Projects & estimating', pagePath: '/procore/commitments-live/maker', pageLabel: 'Commitment Maker', pagePermission: 'procore-commitments', fallbackPermission: 'procore', summary: 'Prepare and validate purchase orders from estimates, workbooks, or approved change orders.', quickStart: 'Select the project and source, then use Preview and Validate to review the proposed lines.' },
  { slug: 'scope-map', title: 'Scope Map', category: 'Projects & estimating', pagePath: '/procore/scope-mapping-review', pageLabel: 'Scope Map', pagePermission: 'procore-scope-map', fallbackPermission: 'procore', summary: 'Review how project scopes match commitment and purchase-order titles.', quickStart: 'Find the project and examine fuzzy matches and their alternatives before relying on the mapping.' },
];

export function getHelpGuideSummaryForPath(pathname: string): HelpGuideSummary | null {
  const path = pathname.length > 1 ? pathname.replace(/\/$/, '') : pathname;
  return HELP_GUIDE_SUMMARIES.find((guide) => guide.pagePath === path) || null;
}

export function helpGuidePath(guide: Pick<HelpGuideSummary, 'slug'>): string {
  return `/help/${guide.slug}`;
}

export function canAccessHelpGuide(permissions: readonly string[], guide: HelpGuideSummary): boolean {
  if (guide.pagePath === '/') return true; // Home is available to every signed-in user.
  const has = (permission: string) => permissions.some((assigned) => assigned.toLowerCase() === permission.toLowerCase());
  return has(guide.pagePermission) || Boolean(guide.fallbackPermission && has(guide.fallbackPermission));
}

export function groupHelpGuidesByCategory<T extends HelpGuideSummary>(guides: readonly T[]): Array<{ category: string; guides: T[] }> {
  const groups = new Map<string, T[]>();
  for (const guide of guides) groups.set(guide.category, [...(groups.get(guide.category) || []), guide]);
  return [...groups.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([category, list]) => ({
    category, guides: [...list].sort((a, b) => a.title.localeCompare(b.title)),
  }));
}
