import { defineGuide } from './defineGuide.ts';

export const projectGuides = [
  defineGuide('dashboard', {
    purpose: 'Get an overview of estimating activity: project statuses, customers, sales, labor hours, and concrete quantities. Use this page to understand the bid pipeline and investigate the projects behind a summary.',
    steps: [{ title: 'Start with the overview', body: 'Read summary cards, Sales Funnel, and Status Breakdown before applying filters.' }, { title: 'Narrow the dates', body: 'Set the date range and open available card or chart details to inspect the jobs. Date filtering uses the later available project update or creation date.' }, { title: 'Review a job or export', body: 'Open job details to check the underlying record. Export Projects to CSV when a project list is needed for review.' }],
    data: ['Stored estimating and bid-board project records feed the summary and detail views. A fast saved summary may load before detailed project records.', 'Each current bid-board record counts as a row. Unlike KPI Win Rate, this page does not collapse records just because their project names match.'],
    terms: [['Sales', 'Estimating/project sales values, not QuickBooks collections.'], ['Approved change orders', 'Approved additions reported separately from original estimating values where labeled.'], ['Status Breakdown', 'The population grouped by current status, not historical status at each month end.'], ['Estimated hours / concrete', 'Planned labor and quantities, not actual timecards or delivered concrete.']],
    example: 'Two contractors bidding the same named job can appear as two bid-board records. Their count here can differ from KPI’s distinct-project win-rate count.',
    checks: ['Check date filters and excluded records before comparing totals. These dates are not Contract Date.', 'If detail takes longer than the summary, allow its load to finish. Refresh and report the filter and job if the result remains inconsistent.'],
  }),
  defineGuide('projects', {
    purpose: 'Find the correct job and inspect project, estimating, budget, bid, and Procore reference information. Use it as an entry point when investigating a particular project rather than a whole-report total.',
    steps: [{ title: 'Find the record', body: 'Use the displayed search and filters to locate the project. Verify the customer as well as the name.' }, { title: 'Check identifiers and status', body: 'Distinguish Bid Board ID from Procore ID. Confirm you are looking at the intended record when similar jobs or phases exist.' }, { title: 'Inspect details', body: 'Open the available project detail sections for estimates, budgets, bids, and changes. Compare their source and status before interpreting amounts.' }],
    data: ['The page combines available project and Procore-derived commercial records through the application’s project services.', 'Estimating bids, proposals, project budgets, and approved changes are different records. Availability depends on project linking and synchronization.'],
    terms: [['Bid Board ID', 'Identifies the estimating opportunity; it is not the execution project ID.'], ['Procore ID', 'Identifies the Procore construction project.'], ['Estimate / Budget', 'Proposed work versus the execution budget. They may differ after changes or conversion.'], ['Status', 'The displayed source’s current project or bid-board state.']],
    example: 'Two rows with similar names can represent separate phases or bids. Check their IDs and customer before treating one as a duplicate.',
    checks: ['For missing detail, verify that the job has the expected linked records and that they have synchronized.', 'A missing value is not necessarily zero. Report the project identifiers and the specific missing section when requesting a correction.'],
  }),
  defineGuide('open-changes', {
    purpose: 'Track open change-management records for your projects and follow them back to Procore for action.',
    steps: [{ title: 'Select the project', body: 'Use All my projects for a broad review or choose the job you are working on.' }, { title: 'Choose a change type', body: 'Review Change Events, PCOs, and PCCOs separately; they describe different stages of the change process.' }, { title: 'Open the source', body: 'Read the number, title, and status, then follow the available link to review the source record.' }],
    data: ['Synchronized Procore change events and change-order records supply the list.', 'The project population follows your My Work context. This is an open-work list, not a complete financial history of every approved change.'],
    terms: [['Change Event', 'A record of potential changed scope or cost needing evaluation.'], ['PCO', 'Potential change order in the contract change workflow.'], ['PCCO', 'Prime contract change order; inspect its status before treating its amount as approved.']],
    example: 'A change event and a related PCO can describe the same underlying work at different stages. Counting both as separate approved revenue would overstate the change.',
    checks: ['Check project access, source status, and synchronization if a record is missing.', 'Do not treat an open or potential change as approved contract value. Confirm approval in the source record.'],
  }),
  defineGuide('estimating', {
    purpose: 'Calculate and save project estimating breakdowns for concrete and reinforcing work, including piers and footer configurations.',
    steps: [{ title: 'Select the project and tool', body: 'Choose the project for the estimate or calculation, then open the appropriate calculator.' }, { title: 'Enter measured quantities', body: 'Check feet versus inches, count of elements, rebar size, spacing, and waste. Review the result before saving.' }, { title: 'Save the breakdown', body: 'Use the calculator’s Save Breakdown action for the selected project and inspect the saved estimate information.' }],
    data: ['Your dimensions and counts combine with stored estimating constants and rebar specifications.', 'Saved estimates and breakdowns live in the application. A saved calculation alone does not establish an approved Procore contract or field order.'],
    terms: [['LF / FT', 'Linear feet or feet; spacing fields may instead use inches.'], ['O.C.', 'On-center spacing between repeated reinforcing elements.'], ['Waste %', 'Allowance above the calculated base quantity.'], ['Rebar weight', 'Derived from length and the stored weight per foot for the chosen bar size.']],
    example: 'Entering 12 in a field labeled feet when you measured 12 inches changes the geometry dramatically. Convert the dimension first, then inspect the resulting quantity.',
    checks: ['Review units, count, spacing, and waste before changing shared constants to fix one estimate.', 'Confirm the project before saving. Calculator output still needs an estimator’s scope review.'],
  }),
  defineGuide('constants', {
    purpose: 'Maintain shared inputs used by estimating tools, including general rates and rebar reference values.',
    steps: [{ title: 'Find the setting', body: 'Choose General Constants or Rebar Specifications and locate the intended name and category.' }, { title: 'Confirm the meaning', body: 'Check whether the value is a rate, percentage, weight per foot, dimension, or overlap before editing.' }, { title: 'Save and review', body: 'Use the available save action and verify the resulting value. Backup to CSV provides a reference copy before a larger review.' }],
    data: ['Values come from the application’s saved estimating constants and rebar reference information.', 'These are shared inputs; changing them can affect later calculations that use them. They are not live supplier quotes.'],
    terms: [['Category', 'Groups a constant such as Labor, Material, General, or Overhead.'], ['Weight (lb/ft)', 'Rebar weight per foot, used when translating length into weight.'], ['Overlap (ft)', 'Stored overlap allowance in feet.']],
    example: 'A per-foot weight must remain in pounds per foot. Entering a total bundle weight in that field would distort calculations for every length using it.',
    checks: ['Check units and names for duplicate or misunderstood constants.', 'Reopen a sample calculation after a change. Do not assume an existing saved estimate has been recalculated automatically.'],
  }),
  defineGuide('line-items', {
    purpose: 'Inspect the estimating and budget detail behind a project’s commercial information. This is useful for tracing sales, quantities, and missing source coverage.',
    steps: [{ title: 'Filter to a project', body: 'Use project, customer, and status filters; Clear Filters removes the restrictions.' }, { title: 'Inspect the overview', body: 'Review budget, commitments, approved changes, proposal counts, and Synced information.' }, { title: 'Expand the detail', body: 'Inspect proposal line items and budget rows, including IDs, units, quantities, costs, and sales.' }],
    data: ['Stored Procore project, estimating proposal, and budget line-item records supply the page.', 'Refresh reloads available application data; the Synced column helps establish how recent the imported source is.'],
    terms: [['Proposal IDs', 'Identify individual estimating proposals, not the project itself.'], ['Qty / UOM', 'Quantity and unit of measure; quantities only compare meaningfully within matching units.'], ['Unit Cost / Sales', 'Cost input versus selling value, not the same measure.'], ['Original Budget / Approved CO', 'Baseline budget and approved changes; do not assume every displayed amount is an additional contract amount.']],
    example: 'A proposal line with 100 units at $20 unit cost has $2,000 base cost. Its sales value can differ because pricing includes other factors.',
    checks: ['Check the selected proposal, source IDs, and last synchronization when details seem missing.', 'Do not add project-level totals once per expanded line; they repeat as context.'],
  }),
  defineGuide('commitments', {
    purpose: 'Review purchase-order and commitment change-order lines by project, vendor, and cost code. Use the line detail to understand what has been committed.',
    steps: [{ title: 'Choose the population', body: 'Filter the project and select All sources, Purchase Order Lines, or Commitment CO Lines.' }, { title: 'Read the parent context', body: 'Verify vendor, commitment number, status, title, and parent value.' }, { title: 'Inspect lines', body: 'Compare description, budget coding, UOM, quantity, unit cost, line amount, and Synced time.' }],
    data: ['Synchronized Procore purchase-order and commitment change-order line records provide the data.', 'The parent contract’s details accompany its lines. The screen is a review of available stored source information.'],
    terms: [['Parent Value', 'The commitment-level amount, which can repeat on several rows.'], ['Line Amount', 'Amount attributable to the individual line.'], ['Source', 'Distinguishes base purchase-order lines from change-order lines.'], ['Commitment Status', 'The source contract state; verify approval before relying on it as an approved obligation.']],
    example: 'A $10,000 purchase order with five displayed lines may repeat $10,000 Parent Value five times. Adding those repeated parent values would incorrectly produce $50,000.',
    checks: ['Check source filters and status before reconciling totals.', 'A committed amount is not proof of a vendor invoice, payment, or field consumption. Use the relevant accounting or productivity detail for those questions.'],
  }),
  defineGuide('commitment-maker', {
    purpose: 'Prepare and validate purchase orders from a primary estimate, uploaded estimate workbook, or approved change order, then create the reviewed result in Procore.',
    steps: [{ title: 'Choose the target and source', body: 'Verify the project. Select Primary Estimate, Upload Estimate Workbook, or Approved Change Order. For a change, select a new or existing purchase order as appropriate.' }, { title: 'Preview and Validate', body: 'Review proposed groups, vendor, coding, descriptions, quantities, units, costs, and warnings. Preview does not create or change records in Procore.' }, { title: 'Create the reviewed result', body: 'Resolve validation errors and inspect totals before using the final create/add action. Creation can produce approved purchase orders and follow-up tasks; confirm the result before leaving.' }],
    data: ['The selected Procore source or worksheet supplies proposed lines. Project budgets, existing commitments, and validated mappings determine where those lines can go.', 'Editing source/grouping choices invalidates the previous preview. An approved-change-order addition to an existing PO adds missing lines rather than creating a commitment change order.'],
    terms: [['Validated Preview', 'The proposed result after checks; it is not yet a created commitment.'], ['Combine proposed purchase orders', 'Groups proposed work together; review the resulting title and lines.'], ['Validation errors', 'Conditions that must be resolved before creation.'], ['Existing Purchase Order', 'A specific target for added change lines; verify number and vendor carefully.']],
    example: 'If an approved change belongs on an existing PO, select that exact PO, preview the missing lines, and review the addition. Choosing New Purchase Order would create a separate obligation.',
    checks: ['If creation times out or the outcome is unknown, inspect the result and existing Procore records before retrying.', 'After modifying groups or source data, preview again. Deleting from a PO changes the source record; distinguish it from simply editing a proposed preview.'],
  }),
  defineGuide('scope-map', {
    purpose: 'Review how project scopes line up with commitment and purchase-order titles. Use this as matching evidence when checking scope-related reporting.',
    steps: [{ title: 'Find the project', body: 'Search by the displayed project or customer information.' }, { title: 'Choose source coverage', body: 'Select both contract tables or one contract type to understand which titles are considered.' }, { title: 'Inspect uncertain matches', body: 'Expand the scope and compare Best Match, Match Type, Score, and Alternatives with number and vendor.' }],
    data: ['Stored project scopes and synchronized contract titles provide candidates.', 'Exact and fuzzy matching compare the available titles; the review does not establish new contractual scope by itself.'],
    terms: [['Exact', 'A direct title match under the matching rules.'], ['Fuzzy', 'A similarity-based candidate needing more careful review.'], ['Score / Alternatives', 'Evidence of relative similarity, not proof of contractual correctness.']],
    example: 'A scope named Site Concrete could resemble multiple purchase orders. Check the vendor and contract number rather than accepting the highest score solely from the name.',
    checks: ['Check source coverage and synchronization if an expected title is absent.', 'A similar title can still be the wrong scope. Report the specific scope and source contract when asking for a mapping correction.'],
  }),
];
