import { defineGuide } from './defineGuide.ts';

export const reportGuides = [
  defineGuide('kpi', {
    purpose: 'Review monthly business performance against goals. Selling work, earning revenue, using labor, and producing profit are separate measures; read the row labels before comparing them.',
    steps: [{ title: 'Choose the year', body: 'Read each table heading. Sales by Month resolves All Years to the current year rather than combining every year.' }, { title: 'Compare actuals with goals', body: 'Compare the same measure and month. Use available project popups to inspect supporting records.' }, { title: 'Check the source', body: 'Saved KPI card values are maintained on Manage. Calculated rows use their reporting sources and can update on a different schedule.' }],
    data: ['The page combines stored project and scheduling information with saved KPI card rows. Cards and tables can finish loading at different times.', 'Win Rate combines saved old-instance history with current bid-board records. Approved reporting groups prevent duplicate contractors and migration copies from becoming separate wins.'],
    terms: [['Win Rate', 'Won distinct projects divided by eligible distinct projects. Won includes Accepted, In Progress, and Complete here. Estimating and excluded records are omitted; To Do, Lost, and Delayed remain in the denominator.'], ['Win Rate months', 'Cumulative January through that month by Created Date, using current statuses. Reporting starts January 2026. This is not a historical month-end status snapshot.'], ['Total percentage', 'Total wins divided by total eligible projects, not an average of monthly percentages. Future months are blank.'], ['Actual versus goal', 'The result versus its target. Read units carefully: dollars, hours, percentages, and lead times are not interchangeable.']],
    example: 'If 12 of 20 eligible distinct projects are won, Win Rate is 60%. That does not mean 60% of estimated dollars were sold. Accepted counts in this KPI even though Financial WIP excludes Accepted.',
    checks: ['Confirm the year and row definition before comparing screens. Dashboard and Financial WIP use different populations and date rules.', 'If cards appear but tables remain blank, wait for loading and check errors. Retry once; report the year, missing table, and time if it persists. Loading blanks are not zero results.'],
  }),
  defineGuide('wip', {
    purpose: 'Understand when planned labor and scheduled sales fall on the calendar. WIP supports workload planning and reconciliation between budgets and schedules. Financial WIP is the separate billing and contract-backlog page.',
    steps: [{ title: 'Set filters', body: 'Select year, customer, project, and month. Clear All Filters restores the broader view.' }, { title: 'Compare views', body: 'Read Table, Gantt, Schedule Timeline, and Scheduled Hours Trend. Monthly Breakdown shows where workload lands.' }, { title: 'Trace differences', body: 'Use Labor Pool Breakdown and its Source column to investigate hours. Download Pool CSV provides the review list.' }],
    data: ['Saved project scopes and monthly, short-term, and long-term schedules supply planning information.', 'Labor budgets and schedule allocations are planning quantities, not QuickBooks invoice totals or actual timecards.'],
    terms: [['Total Budget Hr', 'Labor budget associated with the work.'], ['Scheduled Hours', 'Hours placed into the selected schedule period.'], ['Scheduled Sales Amount', 'Sales allocated through the scheduling calculation; this does not prove an invoice was issued.'], ['Delta / Unreconciled Amount', 'Differences between the compared planning totals; check source coverage and allocations.']],
    example: 'A project with 1,000 budget hours and 700 allocated hours has a 300-hour planning gap. That gap does not establish how many hours have already been worked.',
    checks: ['Check unscheduled scopes, monthly allocations, and date ranges before changing a budget.', 'Use Financial WIP for remaining-to-bill dollars and labor reports to investigate hours already worked.'],
  }),
  defineGuide('financial-wip', {
    purpose: 'Review contracts sold this year, unbilled ongoing work, remaining labor, and how much work the current billing or labor pace can support.',
    steps: [{ title: 'Choose the question', body: 'Use sold detail for new contract volume, backlog detail for work left to bill, Hours remaining by project for labor, and Revenue by month for billing history.' }, { title: 'Check each project’s basis', body: 'Read Status, Sold year source, and Contract source to understand inclusion and value.' }, { title: 'Compare billing and labor', body: 'Read lifetime billed, open A/R, balance, and billed percentage alongside expected, used, and remaining hours.' }],
    data: ['Current estimating/project records supply sold projects. Accepted is excluded; Awarded, In Progress, and Complete are eligible for the sold list.', 'Sold year uses Additional Information Contract Date first, then a year inferred from the job number, then Procore start date. A fallback year does not prove Contract Date was entered.', 'Contract value uses the approved original prime contract when available, otherwise the estimate, plus approved change orders. QBO snapshots supply billing. Labor budgets, approved changes, timecards, and PM closeouts supply hours.'],
    terms: [['Sold this year', 'Contract value for eligible projects in the resolved current sold year, not cash received or this year’s invoices.'], ['Unbilled backlog', 'Positive contract value less lifetime net billed for eligible ongoing work. Complete projects are excluded from actual WIP; overbilling is separate.'], ['Open A/R', 'Already invoiced but unpaid amounts, separate from work not yet billed.'], ['Hours left', 'Labor budget plus approved change-order labor, less used timecards and PM closeout adjustments.'], ['Lead time', 'Unbilled backlog divided by average actual monthly billing, or remaining hours divided by average year-to-date monthly hours. These are pace-based estimates, not promised finish dates.']],
    example: 'A $100,000 contract with $60,000 lifetime net billed has $40,000 unbilled. If $15,000 of invoices remain unpaid, that is A/R; it is not another $15,000 of unbilled work.',
    checks: ['For the wrong sold year, check Additional Information Contract Date and Sold year source. Do not substitute bid creation date.', 'Check status, contract source, approved changes, and billing snapshot before comparing QBO P&L. The screens can have different populations and contract bases.', 'An unavailable value is not a confirmed zero. Check missing source data before interpreting it.'],
  }),
  defineGuide('cost-code-profitability', {
    purpose: 'Compare estimated sales, costs, and margins by category of work, then inspect whole-project QuickBooks actual costs.',
    steps: [{ title: 'Filter the population', body: 'Choose Year, Month, and Procore status. The period groups projects by bid-board Created Date.' }, { title: 'Drill into work', body: 'Select a top-level group, reporting group, and cost code. Review Unassigned items for classification gaps.' }, { title: 'Compare projects', body: 'Review estimated cost, QB actual cost, variance, and profit in Project breakdown. Export CSV for further review.' }],
    data: ['Selected estimating-proposal line items provide item and labor sales and costs. Catalog mappings organize lines into reporting categories.', 'The latest QBO snapshot provides matched project-level actual cost. It does not allocate every QBO cost to estimate cost codes.'],
    terms: [['Group Sales / Cost', 'Estimated line sales and costs, not posted accounting income and expense.'], ['Profit / Margin', 'Sales minus cost; profit divided by sales. Zero sales can leave margin blank.'], ['QB actual cost', 'Recorded project cost over the snapshot window, not necessarily the selected estimate-cohort month.'], ['Actual profit comparison', 'Estimated project sales less recorded actual cost; this differs from QBO posted-income profit.'], ['Unassigned', 'Lines lacking a resolved classification that need mapping review.']],
    example: '$100,000 estimated sales less $80,000 estimated cost gives $20,000 profit and 20% margin. If only $30,000 of costs have posted, a large apparent actual profit is not the unfinished job’s final margin.',
    checks: ['Period filters use bid creation, not invoice date or Contract Date. Compare the same project population and snapshot window.', 'Check unassigned mappings and QBO matches. Missing actual cost does not prove there were no costs.'],
  }),
  defineGuide('qbo-direct-costs', {
    purpose: 'Review monthly field costs and prepare a project bill through the shared QuickBooks service. This workflow includes Create bill in QBO and Update bill in QBO actions; QBO P&L is the separate read-only report.',
    steps: [{ title: 'Choose month and project', body: 'Open a project from the worklist and allow its current review to load.' }, { title: 'Review the draft', body: 'Inspect quantities, rates, product mappings, food total, exclusions, and negative offsets. Resolve listed issues.' }, { title: 'Save the reviewed bill', body: 'Export draft if needed. Create or update when the review permits it. Reconcile QBO changes requires a review first and a separate Update bill action afterward.' }],
    data: ['Synchronized productivity logs and labor, current Cost Catalog rates, and saved mappings/exclusions determine eligible costs. Entered monthly food is included once.', 'The QBO service supplies bill state. A review can become outdated if source data or the existing bill changes.'],
    terms: [['Gross project cost', 'Positive material and labor assigned to the project.'], ['Negative offsets', 'Balancing category lines with no project/customer; these can make the net bill zero while assigning project cost.'], ['Issues / Awaiting mapping', 'Required information is missing or inconsistent; posting is blocked.'], ['Reconciliation needed', 'External bill changes need review before an update.']],
    example: '$2,000 materials plus $1,000 labor can produce $3,000 gross project cost and a $0 net bill after negative offsets. Zero net bill does not mean zero job cost.',
    checks: ['Expand Source and exclusions to review omitted logs and specifically excluded items. Confirm project and month.', 'If saving times out or the outcome is unknown, refresh the review to check the existing bill before retrying.', 'If the application requests a reload, reload before continuing the worklist.'],
  }),
  defineGuide('market-outlook', {
    purpose: 'Use published construction-market signals as context for estimating priorities and future workload. National direction needs comparison with Pennsylvania and regional evidence.',
    steps: [{ title: 'Check dates', body: 'Read the Snapshot date and each source’s reporting period.' }, { title: 'Compare horizons', body: 'Read near-term signals alongside longer-term planning and sector outlooks.' }, { title: 'Open sources', body: 'Follow the publication links and compare their evidence with local customers and opportunities.' }],
    data: ['This is a curated, dated set of indicators, not a continuously updating feed.', 'External industry measures are separate from company sales. Cards identify national proxies and local coverage.'],
    terms: [['Strong / Mixed / Weak / Watch', 'Qualitative readings of the cited signals, not project win probabilities.'], ['Planning versus conversion', 'Planned work may not yet be funded, awarded, or ready to start.'], ['National proxy', 'Broad direction requiring local validation.']],
    example: 'Stronger national planning activity may justify watching a sector, but it does not establish a signed contract or start date for a local project.',
    checks: ['Check source dates before treating a signal as current; opening the page does not refresh the research.', 'Investigate differences between national signals and local customer information.'],
  }),
  defineGuide('reporting', {
    purpose: 'Build a timecard or productivity-log report to trace field records for a project and date range.',
    steps: [{ title: 'Choose the report type', body: 'Select Timecards for labor or Productivity Log for recorded production.' }, { title: 'Set the scope', body: 'Choose a project or All Projects and enter Date From and Date To.' }, { title: 'Run and inspect', body: 'Generate the report, review its rows, and use available output controls when sharing results.' }],
    data: ['Stored projects populate the selector. The reporting service reads available timecards or productivity logs.', 'The selected record type and dates determine coverage; related timecards and production logs are not the same record.'],
    terms: [['Timecards', 'Recorded employee labor and hours.'], ['Productivity Log', 'Field activities and quantities; read each line’s unit.'], ['All Projects', 'A broader population that can take longer to load.']],
    example: 'To investigate a week’s work, run Timecards for that project and week, then a separate Productivity Log report for the same dates.',
    checks: ['Check project, date range, and synchronization when results are empty.', 'Do not add unlike production units together or interpret production quantities as hours.'],
  }),
];

const productivityDetails = {
  purpose: 'Compare purchase-order quantities with field usage and related timecards. Analytics and Field Productivity open the same workspace for investigating overruns, missing entries, and closeout readiness.',
  steps: [{ title: 'Choose a view', body: 'Filter Project, PO Status, Line Activity, and Review Status. Choose By PO or By Description.' }, { title: 'Trace a line', body: 'Expand the project and line. Compare Expected, Used, Remaining, and Progress, then inspect supporting logs and timecards.' }, { title: 'Review closeout', body: 'Use Admin Closeout for eligible completed projects. Mark reviewed after checking the work; this records administrative review.' }],
  data: ['Stored commitments provide expected quantities. Synchronized productivity logs supply usage and linked timecards supply labor context.', 'Closeout status is saved in Analytics. Readiness considers completion and a 30-day cooldown; review does not mean the job has been paid.'],
  terms: [['Expected', 'Planned or committed quantity in the line’s unit.'], ['Used / Remaining', 'Recorded usage and balance; negative remaining can indicate an overrun or a record needing investigation.'], ['Progress', 'Usage relative to expected quantity, not necessarily physical completion, billing, or efficiency.'], ['Review status', 'Waiting for Complete, cooldown, ready for review, and reviewed describe administrative closeout.']],
  example: 'A 100-yard line with 110 yards used is 10 yards over expected. Check logs and scope changes before deciding whether this is extra work, waste, or a duplicate.',
  checks: ['Compare matching units and codes. Quantity and labor hours are different measures even with similar descriptions.', 'Check filters, log assignments, and synchronization for missing activity. If review completion asks for sign-in, sign in and submit again.'],
} satisfies Parameters<typeof defineGuide>[1];

export const productivityGuides = ['analytics', 'field-productivity'].map((slug) => defineGuide(slug, productivityDetails));
